name: simulation
root: ./
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - pylon_camera_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch pylon_camera morhunenko.launch
  - rqt_imgs:
      layout: tiled
      panes:
        - waitForRos; rosrun rqt_image_view rqt_image_view /uav1/fleft/tag_detections_image
        - waitForRos; rosrun rqt_image_view rqt_image_view /uav1/fright/tag_detections_image
  - basler_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch basler_stereopair_driver basler_stereopair_driver.launch is_calibrated:=true
#  - uav_camera_localisation:
#      layout: tiled
#      panes:
#        - waitForRos; roslaunch uav_camera_localisation uav_camera_localisation.launch
  - rviz:
      layout: tiled
      panes:
        - waitForRos; rviz -d $(rospack find basler_stereopair_driver)/rviz/config.rviz
