name: simulation
root: ./
on_project_start: nums=$(shuf -i 1-30 -n 30 | tr '\n' " "); echo "UAV_NUMBERS=($nums)" > /tmp/random_uav_numbers;
pre_window: source /tmp/random_uav_numbers; export UAV_NAME="uav${UAV_NUMBERS[1]}"; export RUN_TYPE=simulation; export UAV_TYPE=f450; export WORLD_NAME=simulation; export SENSORS="garmin_down"
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - pylon_camera_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch pylon_camera morhunenko.launch
  - rqt_imgs:
      layout: tiled
      panes:
        - waitForRos; rosrun rqt_image_view rqt_image_view /${UAV_NAME}/camera_localization/image_left_debug
        - waitForRos; rosrun rqt_image_view rqt_image_view /${UAV_NAME}/camera_localization/image_right_debug
        - waitForRos; rosrun rqt_image_view rqt_image_view /${UAV_NAME}/camera_localization/im_corresp
  - rviz:
      layout: tiled
      panes:
#        - 'history -s "waitForRos; rviz -d $(rospack find basler_stereopair_driver)/rviz/config.rviz"'
        - waitForRos; roscd uav_camera_localization; ./scripts/change_uav.sh ${UAV_NAME}; rviz -d $(rospack find uav_camera_localization)/rviz/device.rviz
  - basler_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch basler_stereopair_driver basler_stereopair_driver.launch is_calibrated:=true
  - uav_camera_localization:
      layout: even-horizontal
      panes:
        - waitForRos; roslaunch uav_camera_localization uav_camera_localization.launch
        - waitForRos; rostopic hz /${UAV_NAME}/basler_left/image_raw
        - waitForRos; rostopic hz /${UAV_NAME}/camera_localization/tdpts
