corresp:
  n_features: 500
  distance_threshold_px: 2
  distances_ratio: 1
  reprojection_error_px: 2
  encoding: "bgr8"

debug_sett:
  debug_images: true
  debug_matches: true
  debug_markers: false
  debug_distances: false

algorithms:
#  triangulation method can be so-called primitive or svd
  triangulation_method: "svd"
#  triangulation_method: "primitive"
