corresp:
  n_features: 300
  distance_threshold_px: 2
  distances_ratio: 1
  reprojection_error_px: 2
  encoding: "bgr8"

debug_sett:
  debug_matches:   true
  debug_markers:   true 
  debug_distances: true

algorithms:
  #  triangulation method can be so-called primitive or svd
  triangulation_method: "svd"
  #  triangulation_method: "primitive"

  #  triangulation method can be so-called primitive or svd
  detection_method: "ORB"
#  detection_method: "FAST"
