corresp:
  n_features: 200
  distance_threshold_px: 3
  distances_ratio: 0.5
  reprojection_error_px: 3
  debug_matches: true
  debug_epipolar: true
  debug_markers: true
  debug_projective_error: true
  debug_distances: true
  # triangulation method can be so-called primitive or svd
  triangulation_method: "svd"
