corresp:
  n_features: 300
  distance_threshold_px: 4
  reprojection_error_px: 4
  distances_ratio: 1
  encoding: "bgr8"

debug_sett:
  debug_matches:   false
  debug_markers:   false
  debug_distances: false

algorithms:
  #  triangulation method can be so-called primitive or svd
  triangulation_method: "svd"
  #  triangulation_method: "primitive"

  #  triangulation method can be so-called primitive or svd
  detection_method: "ORB"
#  detection_method: "FAST"
